//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.22 at 02:38:49 PM CET 
//


package com.miragedev.mononara.core.service.resources;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for dictionary complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="dictionary">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="kana" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="kanji" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="romaji" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tags" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}tag" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="translations" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}translation" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder = {
        "kana",
        "kanji",
        "romaji",
        "tags",
        "translations"
})
public class DictionaryKP {

    protected String kana;
    protected String kanji;
    protected String romaji;
    protected DictionaryKP.Tags tags;
    protected DictionaryKP.Translations translations;

    /**
     * Gets the value of the kana property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getKana() {
        return kana;
    }

    /**
     * Sets the value of the kana property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setKana(String value) {
        this.kana = value;
    }

    /**
     * Gets the value of the kanji property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getKanji() {
        return kanji;
    }

    /**
     * Sets the value of the kanji property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setKanji(String value) {
        this.kanji = value;
    }

    /**
     * Gets the value of the romaji property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getRomaji() {
        return romaji;
    }

    /**
     * Sets the value of the romaji property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRomaji(String value) {
        this.romaji = value;
    }

    /**
     * Gets the value of the tags property.
     *
     * @return possible object is
     *         {@link DictionaryKP.Tags }
     */
    public DictionaryKP.Tags getTags() {
        return tags;
    }

    /**
     * Sets the value of the tags property.
     *
     * @param value allowed object is
     *              {@link DictionaryKP.Tags }
     */
    public void setTags(DictionaryKP.Tags value) {
        this.tags = value;
    }

    /**
     * Gets the value of the translations property.
     *
     * @return possible object is
     *         {@link DictionaryKP.Translations }
     */
    public DictionaryKP.Translations getTranslations() {
        return translations;
    }

    /**
     * Sets the value of the translations property.
     *
     * @param value allowed object is
     *              {@link DictionaryKP.Translations }
     */
    public void setTranslations(DictionaryKP.Translations value) {
        this.translations = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}tag" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "tag"
    })
    public static class Tags {

        protected List<DictionaryTagKP> tag;

        /**
         * Gets the value of the tag property.
         * <p/>
         * <p/>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the tag property.
         * <p/>
         * <p/>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTag().add(newItem);
         * </pre>
         * <p/>
         * <p/>
         * <p/>
         * Objects of the following type(s) are allowed in the list
         * {@link DictionaryTagKP }
         */
        public List<DictionaryTagKP> getTag() {
            if (tag == null) {
                tag = new ArrayList<DictionaryTagKP>();
            }
            return this.tag;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;

            Tags tags = (Tags) o;

            if (tag != null ? !tag.equals(tags.tag) : tags.tag != null) return false;

            return true;
        }

        @Override
        public int hashCode() {
            return tag != null ? tag.hashCode() : 0;
        }
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}translation" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "translation"
    })
    public static class Translations {

        protected List<TranslationKP> translation;

        /**
         * Gets the value of the translation property.
         * <p/>
         * <p/>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the translation property.
         * <p/>
         * <p/>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTranslation().add(newItem);
         * </pre>
         * <p/>
         * <p/>
         * <p/>
         * Objects of the following type(s) are allowed in the list
         * {@link TranslationKP }
         */
        public List<TranslationKP> getTranslation() {
            if (translation == null) {
                translation = new ArrayList<TranslationKP>();
            }
            return this.translation;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;

            Translations that = (Translations) o;

            if (translation != null ? !translation.equals(that.translation) : that.translation != null) return false;

            return true;
        }

        @Override
        public int hashCode() {
            return translation != null ? translation.hashCode() : 0;
        }
    }

    @Override
    public String toString() {
        return "DictionaryKP{" +
                "kana='" + kana + '\'' +
                ", kanji='" + kanji + '\'' +
                ", romaji='" + romaji + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        DictionaryKP that = (DictionaryKP) o;

        if (kana != null ? !kana.equals(that.kana) : that.kana != null) return false;
        if (kanji != null ? !kanji.equals(that.kanji) : that.kanji != null) return false;
        if (romaji != null ? !romaji.equals(that.romaji) : that.romaji != null) return false;
        if (tags != null ? !tags.equals(that.tags) : that.tags != null) return false;
        if (translations != null ? !translations.equals(that.translations) : that.translations != null) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = kana != null ? kana.hashCode() : 0;
        result = 31 * result + (kanji != null ? kanji.hashCode() : 0);
        result = 31 * result + (romaji != null ? romaji.hashCode() : 0);
        result = 31 * result + (tags != null ? tags.hashCode() : 0);
        result = 31 * result + (translations != null ? translations.hashCode() : 0);
        return result;
    }
}
